### ISSUE TITLE
Merge error on ValleyMorphTool on ArcMap 10.8.1

### ISSUE THREAD

**Issue by RockEnthusiast** [turugban/ValleyMorphTool#2]
Hello there when I run the toolbox i'm getting such error which most likely related to python that has been used back then and also the version of ArcMap in which code might need an update about it. Do you have any idea about how this could be solved?

Executing: rivertransect "C:\Users\******\Desktop\ValleyMorphTool-master\test\output.gdb" wsheddem wshedbound ID 50 500 # false
Start Time: Tue Aug 30 23:47:52 2022
Running script rivertransect...
gp.scratchworkspace = C:\Users\******\AppData\Local\Temp\arcC300\rivertransect.gdb
processing watershed ID 2182 (1 of 2) ...
geometric network for streams created ...
flags consisting of source and sink points created ...
longest_riverline created ...
Traceback (most recent call last):
  File "C:\Users\******\Desktop\ValleyMorphTool-master\script\arctoolbox\river_transect.py", line 1844, in <module>
    main(workspace, in_raster, watershedbound, watershedfid, widlist, interval, interval_profile, count_intervalpr, adjust_edge, count_interval)
  File "C:\Users\******\Desktop\ValleyMorphTool-master\script\arctoolbox\river_transect.py", line 1732, in main
    rivercrosslines, midcrosslines, watershedmidline, longest_riverline, valleyfloor, elevationpoints, midcrosslinestable, elevtable, vfwtable = get_riverprofile(in_raster, "local_dem", "local_watershed", wid, interval, interval_profile, count_intervalpr, adjust_edge, count_interval)
  File "C:\Users\******\Desktop\ValleyMorphTool-master\script\arctoolbox\river_transect.py", line 1632, in get_riverprofile
    longaxis = get_longaxis(reduced_raster, wid, lowpoint, farpoint)
  File "C:\Users\******\Desktop\ValleyMorphTool-master\script\arctoolbox\river_transect.py", line 421, in get_longaxis
    endpoints = merge([lowpoint, farpoint], "myendpoints")
  File "C:\Users\******\Desktop\ValleyMorphTool-master\script\arctoolbox\river_transect.py", line 382, in merge
    vt.addrow(input)
RuntimeError: ERROR 999999: Error executing function

**Comment by qianhuan0513** [comment]
how to resolve RuntimeError: Row: \u5b57\u6bb5 shape \u4e0d\u5b58\u5728,
